service: rest-api
 
provider:
  name: aws
  runtime: nodejs12.x 
  memorySize: 128 
  timeout: 10 
  stage: dev 
  region: us-east-1
        
functions: 
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: todos 
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: todos/{id} 
          method: get
          cors: true
  getAll:
    handler: handler.getAll 
    events:
     - http:
         path: todos
         method: get
         cors: true
  update:
    handler: handler.update 
    events:
     - http:
         path: todos/{id}
         method: put
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: todos/{id} 
         method: delete
         cors: true
        
plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation